In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
dfFull = pd.read_csv('ContentMatrixTest.csv', index_col=0)
dfFull.shape

(87518, 73)

In [3]:
dfFull.head()

,userID,gameName,playHours,purchase,appid,rating,english,developer,publisher,average_playtime,...,Steam Leaderboards,Steam Trading Cards,Steam Turn Notifications,Steam Workshop,SteamVR Collectibles,VR Support,Valve Anti-Cheat enabled,linux,mac,windows
0,48028873,100% orange juice,1.8,1.0,282800.0,3.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,88525821,100% orange juice,0.9,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,93644606,100% orange juice,3.1,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,115996656,100% orange juice,2.5,1.0,282800.0,3.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,125017535,100% orange juice,0.7,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [4]:
dfFull.drop_duplicates(subset=['userID', 'gameName'], inplace=True)
names = pd.DataFrame(dfFull[['gameName', 'appid']])
names.drop_duplicates(inplace=True)
names.loc[names.gameName=='left 4 dead 2']

            gameName  appid
43594  left 4 dead 2  550.0

In [5]:
dfFull.loc[dfFull.appid==550].head()

,userID,gameName,playHours,purchase,appid,rating,english,developer,publisher,average_playtime,...,Steam Leaderboards,Steam Trading Cards,Steam Turn Notifications,Steam Workshop,SteamVR Collectibles,VR Support,Valve Anti-Cheat enabled,linux,mac,windows
43594,86540,left 4 dead 2,16.400000,1.0,550.0,3.0,1.0,Valve,Valve,1615.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
43595,298950,left 4 dead 2,16.300000,1.0,550.0,3.0,1.0,Valve,Valve,1615.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
43596,561758,left 4 dead 2,26.000000,1.0,550.0,3.0,1.0,Valve,Valve,1615.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
43597,975449,left 4 dead 2,63.616667,1.0,550.0,3.0,1.0,Valve,Valve,1615.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
43598,1950243,left 4 dead 2,49.000000,1.0,550.0,3.0,1.0,Valve,Valve,1615.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0

In [6]:
# Import all apps list from steam api
AllApps = pd.read_csv('APIdata/AllGames.csv', index_col=0)
AllApps.dropna(inplace=True)
AllApps.drop_duplicates(inplace=True)
AllApps.head()

     appid                                               name
4   216938                      Pieterw test app76 ( 216938 )
5   660010                                              test2
6   660130                                              test3
18  508100  Robotpencil Presents: Setting up Lights in a P...
19  508101  Robotpencil Presents: Setting up Lights in a P...

In [7]:
AllApps.shape

(146533, 2)

In [ ]:
# Join onto existing appd data, main purpose of this is to get appids for all games in the data set
# this will give me a list of appids for which I can requst app metadata from the steamspy api.

AllApps.name = AllApps.name.apply(lambda x: re.sub(r'[^A-Za-z0-9]', '', x))
AllApps.name = AllApps.name.apply(lambda x: x.lower())

In [9]:
AllApps.head()

     appid                                               name
4   216938                      pieterw test app76 ( 216938 )
5   660010                                              test2
6   660130                                              test3
18  508100  robotpencil presents setting up lights in a pa...
19  508101  robotpencil presents setting up lights in a pa...

In [10]:
dfFull.shape

(87518, 73)

In [11]:
dfFull = dfFull.merge(AllApps, how='left', left_on='gameName', right_on='name')
dfFull.head()

,userID,gameName,playHours,purchase,appid_x,rating,english,developer,publisher,average_playtime,...,Steam Turn Notifications,Steam Workshop,SteamVR Collectibles,VR Support,Valve Anti-Cheat enabled,linux,mac,windows,appid_y,name
0,48028873,100% orange juice,1.8,1.0,282800.0,3.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,282800.0,100% orange juice
1,88525821,100% orange juice,0.9,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,282800.0,100% orange juice
2,93644606,100% orange juice,3.1,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,282800.0,100% orange juice
3,115996656,100% orange juice,2.5,1.0,282800.0,3.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,282800.0,100% orange juice
4,125017535,100% orange juice,0.7,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,282800.0,100% orange juice

In [12]:
dfFull.loc[dfFull.appid_x!=dfFull.appid_y].shape

(28644, 75)

In [13]:
noMatch = dfFull.loc[dfFull.appid_x!=dfFull.appid_y, ['appid_x', 'appid_y', 'gameName']].drop_duplicates()

In [14]:
noMatch.dropna(subset='appid_x', inplace=True)

In [15]:
noMatch.loc[noMatch.appid_x.isna()].head(60)

Empty DataFrame
Columns: [appid_x, appid_y, gameName]
Index: []

In [16]:
noMatch.loc[noMatch.appid_y.isna(), 'appid_y'] = noMatch.appid_x

In [17]:
noMatch.head(60)

        appid_x    appid_y                                     gameName
460    224540.0   224540.0                                ace of spades
797    349700.0   582700.0                                    aftermath
798    349700.0  1705720.0                                    aftermath
799    349700.0  1916830.0                                    aftermath
1079   105450.0   105450.0       age of empires iii complete collection
1886    10680.0    10699.0                          aliens vs. predator
2007    34010.0    34019.0                               alpha protocol
3428    33900.0    33909.0                                       arma 2
3429    33900.0    33910.0                                       arma 2
3430    33900.0    33919.0                                       arma 2
4127    33910.0    33900.0                                       arma 2
4128    33910.0    33909.0                                       arma 2
4130    33910.0    33919.0                                       arma 2
8463   104200.0    80820.0                                         beep
9148     7670.0     7700.0                                     bioshock
12411   22350.0    22359.0                                        brink
12798   24740.0    24740.0            burnout paradise the ultimate box
12980    7940.0     7950.0                call of duty 4 modern warfare
13213   42700.0    42749.0                       call of duty black ops
14101   10180.0    10199.0                call of duty modern warfare 2
14488   42680.0    42699.0                call of duty modern warfare 3
14490   42680.0   115300.0                call of duty modern warfare 3
16193   17480.0     5160.0              command and conquer red alert 3
16360  228200.0   228200.0                            company of heroes
16862    9340.0      992.0            company of heroes opposing fronts
18946  273110.0   273110.0                  counterstrike nexon zombies
19979   17300.0    17310.0                                       crysis
20250   17330.0    17311.0                               crysis warhead
20504   17340.0    17312.0                                  crysis wars
20672    2130.0     2114.0    dark messiah of might & magic multiplayer
20757    2100.0     2115.0  dark messiah of might & magic single player
21578   50620.0    50640.0                                   darksiders
24126  224600.0   224600.0                                     defiance
27424   17450.0    17450.0                           dragon age origins
29795   16450.0    16479.0                    f.e.a.r. 2 project origin
30463  286570.0   286570.0                                      f1 2015
30899   22300.0    22309.0                                    fallout 3
31439   22380.0    22449.0                            fallout new vegas
31440   22380.0     5710.0                            fallout new vegas
31441   22380.0     5711.0                            fallout new vegas
34411  227700.0   227700.0                                     firefall
34885  310380.0   310380.0                              fractured space
36627  206210.0   206210.0           gotham city impostors free to play
36866   12100.0    12100.0                         grand theft auto iii
36981   12210.0    12219.0                          grand theft auto iv
36982   12210.0     5152.0                          grand theft auto iv
37363   12120.0    12120.0                 grand theft auto san andreas
37552  271590.0   362003.0                           grand theft auto v
38130   12110.0    12110.0                   grand theft auto vice city
38686    8660.0     8662.0                                gtr evolution
39161  209080.0    82060.0                        guns of icarus online
43083   98400.0   669970.0                                   hard reset
43245  271290.0   271290.0                                       hawken
44431   55100.0     5975.0                                    homefront
46705    1250.0     1259.0                                killing floor
48089  264360.0   264360.0                                      la tale
50179  208090.0   208090.0                                      loadout
50483   50130.0    50409.0                                     mafia ii
50589  213850.0   213850.0                                  magic 2014
52032   17460.0    17460.0                                  mass effect

In [18]:
dfFull.loc[dfFull.appid_x.isna(), 'appid_x'] = dfFull.appid_y

In [19]:
dfFull.loc[dfFull.index.isin(noMatch.index), ['gameName', 'appid_x', 'appid_y']].head(60)

                                          gameName   appid_x    appid_y
460                                  ace of spades  224540.0        NaN
797                                      aftermath  349700.0   582700.0
798                                      aftermath  349700.0  1705720.0
799                                      aftermath  349700.0  1916830.0
1079        age of empires iii complete collection  105450.0        NaN
1886                           aliens vs. predator   10680.0    10699.0
2007                                alpha protocol   34010.0    34019.0
3428                                        arma 2   33900.0    33909.0
3429                                        arma 2   33900.0    33910.0
3430                                        arma 2   33900.0    33919.0
4127                                        arma 2   33910.0    33900.0
4128                                        arma 2   33910.0    33909.0
4130                                        arma 2   33910.0    33919.0
8463                                          beep  104200.0    80820.0
9148                                      bioshock    7670.0     7700.0
12411                                        brink   22350.0    22359.0
12798            burnout paradise the ultimate box   24740.0        NaN
12980                call of duty 4 modern warfare    7940.0     7950.0
13213                       call of duty black ops   42700.0    42749.0
14101                call of duty modern warfare 2   10180.0    10199.0
14488                call of duty modern warfare 3   42680.0    42699.0
14490                call of duty modern warfare 3   42680.0   115300.0
16193              command and conquer red alert 3   17480.0     5160.0
16360                            company of heroes  228200.0        NaN
16862            company of heroes opposing fronts    9340.0      992.0
18946                  counterstrike nexon zombies  273110.0        NaN
19979                                       crysis   17300.0    17310.0
20250                               crysis warhead   17330.0    17311.0
20504                                  crysis wars   17340.0    17312.0
20672    dark messiah of might & magic multiplayer    2130.0     2114.0
20757  dark messiah of might & magic single player    2100.0     2115.0
21578                                   darksiders   50620.0    50640.0
24126                                     defiance  224600.0        NaN
27424                           dragon age origins   17450.0        NaN
29795                    f.e.a.r. 2 project origin   16450.0    16479.0
30463                                      f1 2015  286570.0        NaN
30899                                    fallout 3   22300.0    22309.0
31439                            fallout new vegas   22380.0    22449.0
31440                            fallout new vegas   22380.0     5710.0
31441                            fallout new vegas   22380.0     5711.0
34411                                     firefall  227700.0        NaN
34885                              fractured space  310380.0        NaN
36627           gotham city impostors free to play  206210.0        NaN
36866                         grand theft auto iii   12100.0        NaN
36981                          grand theft auto iv   12210.0    12219.0
36982                          grand theft auto iv   12210.0     5152.0
37363                 grand theft auto san andreas   12120.0        NaN
37552                           grand theft auto v  271590.0   362003.0
38130                   grand theft auto vice city   12110.0        NaN
38686                                gtr evolution    8660.0     8662.0
39161                        guns of icarus online  209080.0    82060.0
43083                                   hard reset   98400.0   669970.0
43245                                       hawken  271290.0        NaN
44431                                    homefront   55100.0     5975.0
46705                                killing floor    1250.0     1259.0
48089                                      la tale  264360.0        NaN
50179                                      loadout  208090.0        NaN
50483                                     mafia ii   50130.0    50409.0
50589                                  magic 2014   213850.0        NaN
52032                                  mass effect   17460.0        NaN

### Bring in app feature data collected from the steamspy api

In [20]:
b1 = pd.read_csv('APIdata/AppMetaDataB1.csv', index_col=0)
b2 = pd.read_csv('APIdata/AppMetaDataB2.csv', index_col=0)
b3 = pd.read_csv('APIdata/AppMetaDataB3.csv', index_col=0)

MetaData = pd.concat([b1, b2, b3])
MetaData.fillna(value=0, inplace=True)
MetaData.shape

(732, 381)

In [21]:
MetaData.head()

,appid,developer,publisher,1980s,1990's,2.5D,2D,2D Fighter,2D Platformer,3D,...,NSFW,Sailing,Skiing,Snow,Snowboarding,Social Deduction,Video Production,Vikings,Warhammer 40K,Werewolves
0,282800,Orange_Juice,Fruitbat Factory,0.0,0,0,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,223850,UL,UL,0.0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,251570,The Fun Pimps,The Fun Pimps Entertainment LLC,0.0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,250420,Archive Entertainment,Archive Entertainment,0.0,0,0,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,278360,Gone North Games,Coffee Stain Publishing,0.0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
dfFull.drop_duplicates(subset=['userID', 'gameName', 'playHours', 'appid_x'], inplace=True)

There were some duplicate appids for individual games in the data pulled from steams api, resulting in duplicates and issues when joining with steamspy data. A quick pull of data from steamspy's api for these duplicate appids revealed which ones returned valid data and which did not. The invalid appid duplicates were dropped from the data.

In [23]:
fun = dfFull.loc[dfFull.duplicated(subset=['userID', 'gameName', 'playHours'], keep=False)]
fun.gameName.unique()

array(['aftermath', 'bioshock', 'borderlands',
       'call of duty modern warfare 3', 'command and conquer red alert 3',
       'crysis wars', 'dark messiah of might & magic multiplayer',
       'dark messiah of might & magic single player', 'darksiders',
       'gtr evolution', 'hard reset', 'napoleon total war',
       'red orchestra 2 heroes of stalingrad single player',
       "sid meier's civilization iv beyond the sword",
       "sid meier's civilization iv warlords", 'super meat boy',
       'the last remnant', 'the walking dead',
       'the witcher enhanced edition',
       "tom clancy's splinter cell conviction", 'total war shogun 2',
       'trine', 'universe sandbox'], dtype=object)

In [24]:
fun.loc[fun.gameName=="universe sandbox"].appid_x.value_counts()

80776.0     52
230290.0    52
Name: appid_x, dtype: int64

In [25]:
dfFull.loc[dfFull.gameName=='portal 2', 'appid_x'].value_counts()

620.0    563
Name: appid_x, dtype: int64

In [26]:
# Dropping duplicated invalid appids
dfFull = dfFull.loc[~dfFull.appid_x.isin([582700, 1705720, 7700, 8950, 42699, 115300, 5160, 17312, 2115, 50620, 10540, 
                                           34009, 8662, 669970, 34039, 212541, 8804, 34460, 34450, 40809, 1989070, 23319, 
                                           581510, 9810, 33220, 201270, 35709, 80776])]

In [27]:
dfFull.loc[dfFull.duplicated(subset=['userID', 'gameName'])]

,userID,gameName,playHours,purchase,appid_x,rating,english,developer,publisher,average_playtime,...,Steam Turn Notifications,Steam Workshop,SteamVR Collectibles,VR Support,Valve Anti-Cheat enabled,linux,mac,windows,appid_y,name
20623,561758,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20625,975449,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20627,9128105,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20629,9823354,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20631,10253354,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20633,11403772,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20635,12610800,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20637,20772968,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20639,26762388,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20641,31669242,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20643,33013552,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20645,33282871,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20647,33865373,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20649,38049880,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20651,47457723,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20653,50811344,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20655,50818751,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20657,63157803,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20659,73835640,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20661,79073449,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20663,83770731,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20665,90272527,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20667,105503045,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20669,123101539,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer
20671,138482130,dark messiah of might & magic multiplayer,0.0,1.0,2130.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2130.0,dark messiah of might & magic multiplayer

In [28]:
dfFull.appid_x.isna().sum()

2421

In [29]:
b = dfFull.loc[~dfFull.appid_x.isin(MetaData.appid), ['gameName', 'appid_x']]
b.drop_duplicates(inplace=True)
b.loc[b.appid_x.isna()].head(32)

                                                gameName  appid_x
340                       a.v.a alliance of valiant arms      NaN
411                                        ace of spades      NaN
897                         age of empires ii hd edition      NaN
1014                  age of empires ii hd the forgotten      NaN
1293                                             airmech      NaN
10400                                      blender 2.76b      NaN
11408     borderlands dlc claptraps new robot revolution      NaN
12660                                       brtal legend      NaN
14197          call of duty modern warfare 2 multiplayer      NaN
16495              company of heroes (new steam version)      NaN
22637                                          dcs world      NaN
26175                              divinity original sin      NaN
26778                         don't starve together beta      NaN
29172                                      endless space      NaN
34323                                           firefall      NaN
34831                                    fractured space      NaN
34986                       freestyle2 street basketball      NaN
39540                                               h1z1      NaN
43170                                             hawken      NaN
45047                       infestation survivor stories      NaN
48063                                            la tale      NaN
50065                                            loadout      NaN
50556                                        magic 2014       NaN
51949                                 marvel heroes 2015      NaN
52872                              medieval ii total war      NaN
54996                     mortal kombat komplete edition      NaN
56088                                           neotokyo      NaN
56128                                             nether      NaN
56743                                            nosgoth      NaN
72178  sid meier's civilization v scrambled continent...      NaN
74577                                          spintires      NaN
74723                      spooky's house of jump scares      NaN

In [30]:
# Any remaing games with missing appids are dropped
dfFull.dropna(subset=['appid_x'], inplace=True)

In [31]:
dfFull.loc[(dfFull.appid_x.isna())&(dfFull.appid_y.isna()), ['appid_x', 'appid_y']].sum()

appid_x    0.0
appid_y    0.0
dtype: float64

In [32]:
dfFull.shape

(85045, 75)

In [33]:
dfFull.isna().sum()

userID           0
gameName         0
playHours        0
purchase         0
appid_x          0
             ...
linux        22695
mac          22695
windows      22695
appid_y       2087
name          2087
Length: 75, dtype: int64

In [34]:
dfFull.drop_duplicates(subset=['userID', 'gameName'], inplace=True)
dfFull.shape

(85020, 75)

In [35]:
dfFull.drop(columns=['appid_y', 'name'], inplace=True)
dfFull.rename(columns={'appid_x':'appid'}, inplace=True)
dfFull.head()

,userID,gameName,playHours,purchase,appid,rating,english,developer,publisher,average_playtime,...,Steam Leaderboards,Steam Trading Cards,Steam Turn Notifications,Steam Workshop,SteamVR Collectibles,VR Support,Valve Anti-Cheat enabled,linux,mac,windows
0,48028873,100% orange juice,1.8,1.0,282800.0,3.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,88525821,100% orange juice,0.9,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,93644606,100% orange juice,3.1,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,115996656,100% orange juice,2.5,1.0,282800.0,3.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,125017535,100% orange juice,0.7,1.0,282800.0,2.0,1.0,Orange_Juice,Fruitbat Factory,1678.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

### Add meta data gathered from steamspy api
Now that all games have been linked to thier appropirate appid we can pull in game feature data gathered from the steamspy api. This data includes tags, genres, developers, and publishers.

In [36]:
dfFull.appid.isna().sum()

0

In [37]:
dfFull.appid.isna().sum()

0

In [38]:
# Export for now, once I have steamspy details, I can come back to this notebook and add them to the data.
# Purpose of this is to limit the calls made to the steamspy api to only games included in the data set used for modeling.
# dfFull.to_csv('ContentMatrix2.csv')

## Import and concatenate the steamspy data

In [39]:
b1 = pd.read_csv('APIdata/AppMetaDataB1.csv', index_col=0)
b2 = pd.read_csv('APIdata/AppMetaDataB2.csv', index_col=0)
b3 = pd.read_csv('APIdata/AppMetaDataB3.csv', index_col=0)
b4 = pd.read_csv('APIdata/AppMetaDataB4.csv', index_col=0)

In [40]:
MetaData = pd.concat([b1, b2, b3, b4])
MetaData.shape

(788, 384)

In [41]:
# Now remove old metadata columns from full df and merge with new meta data
dfFull = dfFull[['userID', 'gameName', 'playHours', 'rating', 'appid']]
dfFull.shape

(85020, 5)

In [42]:
dfFull = dfFull.merge(MetaData, how='left', on='appid')
dfFull.shape

(85020, 388)

### Remove any games that are free to play
Some of these games are automatically added to user's accounts and others will be purchased and never played, or played very infrequently.

In [47]:
dfFull.to_csv('ContentMatrix2Test.csv')